### ISSUE TITLE
Is it possible to set up Gemini API key?

### ISSUE THREAD

**Issue by DelmarHuang** [Tiendil/feeds.fun#168]
Since it is free for the moment, I wonder if this is possible. Thank you for your wonderful work!

**Comment by Tiendil** [comment]
Hi! Thank you for your kind words.

>Is it possible to set up Gemini API key? 

Right now, the project uses only OpenAI API => the Gemini API key will not work. 

This decision was made to speed up the development because it was more important to prove the concept. LLM backend can always be replaced.

I don't want to lock Feeds Fun on a single LLM vendor (OpenAI, Google, etc.). I plan to do something about that this year, but I do not know when exactly. Your question definitely increases the priority of this task.

Also, my big hopes are in the area of open-source LLMs.

The tag system is based on the actors approach => adding other LLMs is not hard. But in case of adding the second paid LLM some additional refactoring will be required to support independent tracking of multiple types of keys and their usage.

**Comment by Tiendil** [comment]
Integration with Gemini done as a part of gh-245.

Will appear on https://feeds.fun right after the nearest release.

If you are self-hosting the reader, see [CHANGELOG.md](https://github.com/Tiendil/feeds.fun/blob/main/CHANGELOG.md) for details about migration.
